### ISSUE TITLE
Ignore deprecated inputs

### ISSUE THREAD

**Issue by axel-op** [typesafegithub/github-actions-typing#110]
In `action.yaml`, it is possible to mark an input as deprecated by providing a [`deprecationMessage`](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs).

Currently, this action marks as invalid any input in `action.yaml` that is missing from `action-types.yaml`, including those with a deprecation message.

Would it be possible to ignore deprecated inputs, so that we wouldn't have to add those inputs in `action-types.yaml`?

**Comment by krzema12** [comment]
Hi @axel-op!

Technically it's possible, but I'm not sure if it's the right thing. Why deprecating a given input should result in having no type for it? I compare it to e. g. Java where one can mark a given method argument as `@Deprecated` and it doesn't mean that it should not be typed. It just means that it was once used and the deprecation process has started which will eventually result in removing this piece of API. It would be nice if you presented your way of thinking.

**Comment by axel-op** [comment]
My request comes from the fact that I'm about to add the typing file to an existing action with deprecated parameters that are soon to be removed. But after all, the easiest way to deal with this is probably just to remove these inputs completely :)

**Comment by krzema12** [comment]
@axel-op another option would be to add the typings to the deprecated inputs as well, it's not that much work right? 😀 The difference is that removing deprecated inputs will break your clients, unless of course you communicate it properly viaa version bump.
